# Generated by Django 4.2.7 on 2024-03-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("form_service", "0013_alter_modelform_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="memeber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status_member",
                    models.CharField(
                        choices=[("1", "สมาชิกรายวัน"), ("2", "สมาชิกรายเดือน")],
                        max_length=3,
                    ),
                ),
                ("price", models.CharField(max_length=20)),
                (
                    "modelform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="form_service.modelform",
                    ),
                ),
            ],
        ),
    ]
