# Generated by Django 4.2.7 on 2024-03-25 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("form_service", "0013_alter_modelform_status"),
        ("member_app", "0002_alter_memeber_status_member"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="memeber",
            new_name="MemberModel",
        ),
    ]
