# Generated by Django 4.2.7 on 2024-03-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member_app", "0003_rename_memeber_membermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermodel",
            name="status_member",
            field=models.CharField(
                choices=[("1", "สมาชิกรายวัน"), ("2", "สมาชิกรายเดือน")],
                default=1,
                max_length=300,
            ),
        ),
    ]
