# Generated by Django 4.2.7 on 2024-03-25 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("member_app", "0004_alter_membermodel_status_member"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membermodel",
            name="modelform",
        ),
    ]
