# Generated by Django 4.2.7 on 2024-03-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member_app", "0005_remove_membermodel_modelform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermodel",
            name="status_member",
            field=models.CharField(
                choices=[("1", "สมาชิกรายวัน"), ("2", "สมาชิกรายเดือน")],
                default="1",
                max_length=1,
            ),
        ),
    ]
