# Generated by Django 4.2.7 on 2024-03-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member_app", "0008_membermodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membermodel",
            name="price",
        ),
        migrations.AddField(
            model_name="membermodel",
            name="address_member",
            field=models.TextField(blank=True, null=True),
        ),
    ]
