# Generated by Django 4.2.7 on 2024-03-28 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("member_app", "0009_remove_membermodel_price_membermodel_address_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membermodel",
            name="status_member",
            field=models.IntegerField(
                choices=[(1, "สมาชิกรายวัน"), (2, "สมาชิกรายเดือน")], default=1
            ),
        ),
    ]
