# Generated by Django 4.2.7 on 2024-03-29 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("form_service", "0013_alter_modelform_status"),
        ("member_app", "0010_alter_membermodel_status_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="membermodel",
            name="modelform",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="form_service.modelform",
            ),
        ),
    ]
